version: 2
builds:
  - id: "affine-build"
    builder: rust
nfpms:
  - builds:
      - "affine-build"
    vendor: dawnmagnet
    homepage: "https://github.com/DawnMagnet/affine-break.git"
    maintainer: "Dawn Magnet <axccjqh@qq.comm>"
    description: "Disk Usage/Free Utility"
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
