version: 2
builds:
  # You can have multiple builds defined as a yaml list
  - #
    # ID of the build.
    #
    # Default: Project directory name.
    id: "my-build"

    # Use rust.
    builder: rust
nfpms:
  - builds:
      - duf
    vendor: muesli
    homepage: "https://fribbledom.com/"
    maintainer: "Christian Muehlhaeuser <muesli@gmail.com>"
    description: "Disk Usage/Free Utility"
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin