version: 2

before:
  hooks:
    - rustup default stable
    - cargo install --locked cargo-zigbuild
builds:
  - id: "affine-build"
    builder: rust
    targets:
      - "x86_64-apple-darwin"
      - "x86_64-pc-windows-gnu"
      - "aarch64-apple-darwin"
      - "x86_64-unknown-linux-musl"
      - "aarch64-unknown-linux-musl"

nfpms:
  - builds:
      - "affine-build"
    vendor: dawnmagnet
    homepage: "https://github.com/DawnMagnet/affine-break.git"
    maintainer: "Dawn Magnet <axccjqh@qq.com>"
    description: "Decrypt a ciphertext using the affine cipher, you should provide two pairs of ciphertext and plaintext characters"
    license: MIT
    formats:
      - apk
      - deb
      - rpm
      - archlinux

    bindir: /usr/bin
