[package]
name = "affine-break"
version = "1.5.0"
edition = "2021"
authors = ["DawnMagnet"]
description = "a tools break affine cipher"
license = "MIT"

[dependencies]
clap = { version = "4.5.34", features = ["derive"] }
